hub:
  #cookieSecret: secret: openssl rand -hex 32
  baseUrl: /jupyterhub-internal/
  db:
    type: sqlite-memory
  service:
    annotations:
      prometheus.io/path: /jupyterhub-internal/hub/metrics
#  extraConfig:

debug:
  enabled: true

#auth: secret

proxy:
  #secretToken: secret: openssl rand -hex 32
  service:
    type: ClusterIP

singleuser:
  image:
    name: imagedata/idr-notebooks
    tag: latest
    pullPolicy: Always
  startTimeout: 1800
  # Set relatively low defaults for CPU and memory
  # Change them for individual images in KubeSpawner.profile_list
  cpu:
    limit: 1
    guarantee: 0.1
  memory:
    limit: 1G
    guarantee: 512M
  storage:
    type: NONE
    extraVolumes:
    - name: jupyterhub-sharedscratch-rw
      persistentVolumeClaim:
        claimName: jupyterhub-internal-storage-nfs-volume
    extraVolumeMounts:
    - name: jupyterhub-sharedscratch-rw
      mountPath: /home/jovyan/shared
      subPath: shared
  cmd: jupyter-labhub
  profileList:
  - display_name: 'snoopycrimecop/jupyter-docker:master_merge_daily'
    kubespawner_override:
      singleuser_image_spec: 'snoopycrimecop/jupyter-docker:master_merge_daily'

  - display_name: 'snoopycrimecop/idr-notebooks:master_merge_daily'
    kubespawner_override:
      singleuser_image_spec: 'snoopycrimecop/idr-notebooks:master_merge_daily'

  - display_name: 'snoopycrimecop/idr-notebooks:itr_merge_daily'
    description: itr_merge_daily with 2 cpu 6.5 GB memory
    kubespawner_override:
      singleuser_image_spec: 'snoopycrimecop/idr-notebooks:itr_merge_daily'
      cpu_limit: 2
      mem_limit: '6.5G'

  - display_name: 'imagedata/idr-notebooks:latest'
    kubespawner_override:
      singleuser_image_spec: 'imagedata/idr-notebooks:latest'

  - display_name: 'imagedata/idr-notebooks:VAE-0.5.2'
    kubespawner_override:
      singleuser_image_spec: 'imagedata/idr-notebooks:VAE-0.5.2'

  - display_name: 'snoopycrimecop/training-notebooks:master_merge_daily'
    kubespawner_override:
      singleuser_image_spec: 'snoopycrimecop/training-notebooks:master_merge_daily'

  - display_name: 'openmicroscopy/training-notebooks:latest'
    kubespawner_override:
      singleuser_image_spec: 'openmicroscopy/training-notebooks:latest'

  - display_name: 'openmicroscopy/training-notebooks:0.3.0'
    kubespawner_override:
      singleuser_image_spec: 'openmicroscopy/training-notebooks:0.3.0'

  extraEnv:
    IDR_HOST: idr.openmicroscopy.org
    IDR_USER: public

# Disable image pre-puller
prePuller:
  hook:
    enabled: false

ingress:
  enabled: true
  hosts:
  - ome-lochy.openmicroscopy.org
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
  tls:
  - hosts:
    - ome-lochy.openmicroscopy.org
